[project]
name = "sdg"
version = "0.1.0"
description = "Synthetic Data Generator System"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.0",
]
